### ISSUE TITLE
Proxy complains every minute about cache quota propagation that fails for a bunch of namespaces

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#823]
```
Oct 04 15:07:46 HPRM-test alba[3095]: 2017-10-04 15:07:46 330217 +0000 - HPRM-test - 3095/0000 - alba/proxy - 202889 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_001179193" was not found
Oct 04 15:07:46 HPRM-test alba[3095]: 2017-10-04 15:07:46 330294 +0000 - HPRM-test - 3095/0000 - alba/proxy - 202890 - info - (ignoring) cache quota propagation failed: namespace no longer exists
Oct 04 15:07:46 HPRM-test alba[3095]: 2017-10-04 15:07:46 330353 +0000 - HPRM-test - 3095/0000 - alba/proxy - 202891 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_001179050" was not found
Oct 04 15:07:46 HPRM-test alba[3095]: 2017-10-04 15:07:46 330371 +0000 - HPRM-test - 3095/0000 - alba/proxy - 202892 - info - (ignoring) cache quota propagation failed: namespace no longer exists
Oct 04 15:07:46 HPRM-test alba[3095]: 2017-10-04 15:07:46 330437 +0000 - HPRM-test - 3095/0000 - alba/proxy - 202893 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_001179195" was not found
Oct 04 15:07:46 HPRM-test alba[3095]: 2017-10-04 15:07:46 330456 +0000 - HPRM-test - 3095/0000 - alba/proxy - 202894 - info - (ignoring) cache quota propagation failed: namespace no longer exists
Oct 04 15:07:46 HPRM-test alba[3095]: 2017-10-04 15:07:46 330507 +0000 - HPRM-test - 3095/0000 - alba/proxy - 202895 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_001179217" was not found
...
```
...
```
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630273 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203546 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_001179050" was not found
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630351 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203547 - info - (ignoring) cache quota propagation failed: namespace no longer exists
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630430 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203548 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_001179086" was not found
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630455 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203549 - info - (ignoring) cache quota propagation failed: namespace no longer exists
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630522 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203550 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_000806835" was not found
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630542 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203551 - info - (ignoring) cache quota propagation failed: namespace no longer exists
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630621 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203552 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_001178795" was not found
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630644 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203553 - info - (ignoring) cache quota propagation failed: namespace no longer exists
Oct 04 15:08:43 HPRM-test alba[3095]: 2017-10-04 15:08:43 630710 +0000 - HPRM-test - 3095/0000 - alba/proxy - 203554 - info - Nsm_host_access.with_namespace_id: namespace "a4f9175a-7b32-4f6e-9a88-e3d79f819e4d_001179215" was not found
...
```

**Comment by toolslive** [comment]
Yes. 
```
... (ignoring) cache quote propagation failed: namespace no longer exists
```
Seen about 450k entries per day on a certain node.

**Comment by toolslive** [comment]
that particular log line should be gone in 1.6.1 because the underlying issue was fixed.

**Comment by domsj** [comment]
@toolslive sure this is fixed in 1.6.1? (if you're referring to https://github.com/openvstorage/alba_ee/pull/128/files : as far as I understand it doesn't make this logging go away)
or am I missing something?

**Comment by wimpers** [comment]
@toolslive @domsj  what is the status now? Fixed, Not fixed?

**Comment by domsj** [comment]
fixed by #185, will be in alba 1.5.21
